# Generated by Django 4.0.6 on 2022-07-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='age',
            new_name='price',
        ),
    ]
