# Generated by Django 4.0 on 2022-07-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_age_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='title',
        ),
    ]
